apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:M/Xlb29atGs=,iv:Y0TGgegFPa9RwgwXGj75x8taqjZmg2k42d15dRFNQbU=,tag:M0L+WN7aoR4IkIq+XNXVuA==,type:str]
    password: ENC[AES256_GCM,data:AMDlsFhYEu0IZ4MJHau4DA==,iv:D3/soP/jR3tTIrgDCj9WsfK5KksobIwZyYGGNrPdzps=,tag:epzCcXbGRN2OsmhszM1DMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-10T08:03:29Z"
    mac: ENC[AES256_GCM,data:4OcbVonw/cPrepjxWoAzlRpfCvi0y2gmTq1KgbbYpXAdlcwAG5WeOzhvgukBg+9Zt55uaI6rZ8UcOFnaJBxlvN1VrxLu/MZ9hsgN5uVelSS/acBQa7U+fTpVCU8Bot5GuQCHtRB4EBRqIXqvvqkkkCQZD8xziSO7WiDdfEDZ9rg=,iv:/XA5tdqRVxbVe8OOzFthEu4V5cMGpCCp1DQZcDG30d4=,tag:uJOotJAMpJEdDn1VDQ7XAg==,type:str]
    pgp:
        - created_at: "2021-08-10T08:03:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA17LOzZujEHzARAAyopEhWrKeDFBcBYkmEIdyjSghbAZMGA6Sde1ye4CMTJ8
            4OX3wyu+yiQboehdjU+UEn1GPdvN2JZtBRlN1ttv0hDUttbbmdBpjZ6WTTYDqJ+N
            smsL0V0Ir5bu4oXGKe2EtD1qSy6C6um60MzjrBw/Q3k5ARS28EkaEmeyLgmG7Irp
            K2voTTj4vWmOWUcjYdeARMoZZ5su5+ztWrDr7mQm3gATXBnKoDyf+Mr6M0LDJ2Dd
            wR6QA1PEJaBHtl2MSLWSbNlDMWiWFZVO/fOXCLaQV0zDXNynvpI1zApHAldSwBKS
            WUuZFZrzLUy2OGT/lrRLKyv+GHIr6jx7uZCetfE2ZPIYP9THib4Ia37P3q1bnQ/k
            Hx7nkz9N31Mbd6t+X0chJcNa1+vxxGuUvFBv4HBt6UnuJqsrQIM9uxRYUyY8N/aM
            ZbOU3UAGR3v8sSnPWy0HpWlaMgKyJ4UAwdDJ5kItzmaX5KtHJZfYWO8PFYRPAGKX
            eQHQbkzy5vCh3qbZYJIYFtwsgMfO8mXPE0qX+9yxqhenIU/ifCWsKDDLZfmNIjaF
            7YdRZfOhPgXT6GM9mSInFOxVgUaQfDZ8cZMBgREdEDWZNTxn6JGPom68GwchQH0e
            U400AtwxieCKQ/uIiYq5nKQ/wNarVGOg91g1Gw1syN5q6LjqUPtt1qdh5F01p3XS
            UQGAkuzitLC8rrqMlgQS8/zs1LiRh2cG8MoU0LTley23PviJy5d3zgtvxObaN2pp
            RXkTI0pn0DtNyCbtVzxRTxHUNj/YgSL8KZ3KGoDgZpaZRg==
            =C48u
            -----END PGP MESSAGE-----
          fp: C517F5FC2811C3AE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
